### ISSUE TITLE
installation steps request

### ISSUE THREAD

**Issue by forcecity** [pv2b/netbox-plugin-mclag#1]
Hello @pv2b 
I came from https://github.com/netbox-community/netbox/discussions/6116 and find your plugin. I think this is what i'm looking for. But when i tried to install and use it, i always got "ModuleNotFoundError: No module named 'netbox.models'" error. I couldn't find the installation steps and netbox version requirement from readme file.

My netbox is running at v2.10.4.. I don't know if it is because the version is too low. Maybe you could give some hints. Thanks a lot!!

**Comment by pv2b** [comment]
Hello and thanks for the interest!

However, I have developed the plugin for NetBox 3.6, and I don't intend to put in any work to support older versions.

**Comment by pv2b** [comment]
However, on second thought, you're right that there are currently no installation instructions or formal version requirement, and it's reasonable to expect that, so I'll keep this issue open to track that.

But, until then, I don't intend to support anything older than NetBox 3.6.

**Comment by pv2b** [comment]
Installation instructions have been added by #2 (thanks @bsavardmsk for your contributions!) and https://github.com/pv2b/netbox-plugin-mclag/commit/d254c665047fbc0ff344c83fa0f224a9c78a4b4a has added a section on supported versions.

If you want, you can double-check that you've installed the plugin correctly using those steps to exclude any mistakes in the installation, but Netbox 2.10.4 is a very old version and I would not be surprised if it ends up not to work even when installed according to these instructions.

If you do end up getting it to work with older Netbox, and the changes aren't too disruptive, I'd welcome a PR with your proposed changes to backport it.
